// APELAM FUNC. 'TEST('NUME_TEST', FUNC_IN_CARE_IMPLEMENTAM_TESTUL)':
test('Primul meu Test', () => {
    // ARUNCAM O EXCEPTIE:
    throw new Error('Ceva a esuat!');
});